<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?= $title ?></title>

        <?= EdsonOnildo\Tpl\Tag\Evaluate::style('style.css') ?>
        <script src="<?= EdsonOnildo\Tpl\Tag\Evaluate::assets('css/test.css') ?>"></script>
    </head>
    <body>
        <header>
            <h1><?= $title ?></h1>
        </header>

        <main>
            
    <?= $status ? 'HAHHA' : ':\\' ?>

            
            <h1>Credits</h1>
<ul>
    <?php foreach ($authors as $author) { ?>
        <li><a href="<?= $author->page ?>"><?= $author->name ?></a></li>
    <?php } ?>
</ul>

        </main>

        <footer>
            <?= date('Y') ?> PHP-Template-Engine
        </footer>
        
        <?= EdsonOnildo\Tpl\Tag\Evaluate::script('script.js') ?>
    </body>
</html>


